<?php
    $title = 'An error occurred';
    $this->headTitle($title);
?>
<section class="header-wrapper text-center">
    <h1 class="margin-b1 position-r header-hr">An error occurred!</h1>
</section>
<section class="default-widget bg-white" style="padding-top: 3rem;padding-bottom: 4.5rem;">
    <div class="grid-container">
        <div class="grid-x align-middle grid-padding-x grid-padding-y">
            <div class="medium-12 cell">
                <h2 class="text-center error-404-text"><span class="error-404-text-small">Error code </span>500</h2>
            </div>
        </div>
    </div>
</section>
<section class="default-widget cta bg-blue text-center">
    <div class="grid-container">
        <h2>Need more information?</h2>
        <div class="grid-x grid-padding-x">
            <div class="small-12 medium-4 large-2 cell medium-offset-4 large-offset-5">
                <a href="<?= $this->url('contact-us'); ?>" title="Contact Us"><button type="button" name="button" class="button secondary medium expanded">Get in Touch</button></a>
            </div>
        </div>
    </div>
</section>
