<?php
        $this->headMeta('Make money with network marketing, Earn from £440 to £5,000+ per month EXTRA, part-time working from home, Be your own boss, Flexible hours.','description');

        $this->headMeta('Flexible hours, Cash paid weekly, Be your own boss, affiliate marketing,Make Money with Network Marketing, Make Money with affiliate Marketing','keywords');

        $this->headMeta('index, follow','robots');

    $title = 'Make Money With Affiliate Network';
    $this->headTitle($title);
?>
<section class="main-widget" >
    <div class="grid-container">
        <div class="grid-x grid-padding-x">
            <div class="medium-5 cell medium-order-2 form-cont hide-for-small-only">
                <script>
                    function isValidPhone(phone_number)
                    {
                    var phone = phone_number.replace(/[\(\)\.\-\ ]/g, '');
                    if (phone == "") { return false;
                    } else if (isNaN(parseInt(phone))) { return false;
                    } else if (phone.length < 10 || phone.length >= 15) { return false;
                    } return true;
                    }
                    function isValidEmail(email)
                    {
                    var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
                    if(reg.test(email) == false) { return false; } return true;
                    }
                    function checkForm(myForm) {
                     var errors = "";
                    if (myForm.f_firstname.value == "") errors = "<li>Please enter your First Name.</li>";
                    if (myForm.f_lastname.value == "") errors += "<li>Please enter your Last Name.</li>";
                    if (!isValidEmail(myForm.f_email.value)) errors += "<li>Please enter a Valid Email.</li>";
                    if (!isValidPhone(myForm.f_phone.value)) errors += "<li>Please enter a Valid Phone Number.</li>";

                    if (errors != "") {
                        $('#error').show();
                        $('#error ul').html(errors).show();
                        return false;
                    } else {
                        $('#error').hide();
                        $('#error ul').html('').show();
                        return true;
                        }
                     }
                </script>
                <div data-sticky-container>
                    <div data-sticky data-top-anchor="60" data-margin-top="1">
                        <form id="form" action="http://mela-recruit.co.uk.7figuresecrets.com/ms/external" method="post" onSubmit="javascript:return checkForm(this);" class="form-wrapper">
                            <input type="hidden" name="event" value="lp_form">
                            <input type="hidden" name="sub_event" value="visit1">
                            <input type="hidden" name="revisit_event" value="revisit1">
                            <input type="hidden" name="val_required" value="f_firstname,f_lastname,f_email,f_phone">
                            <input type="hidden" name="category_id" value="6465">
                            <input type="hidden" name="campaign_id" value="3305">
                            <h2 class="text-centerxxx">Please fill in the form below to get more information about our offers</h2>
                            <div class="grid-x grid-padding-x">
                                <div class="medium-12 cell" id="error">
                                    <div class="callout alert-danger">
                                        <ul>
                                            <li></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="large-6 cell">
                                    First Name<span class="required">*</span><input name="f_firstname" value="<?=$_SESSION['first_name']?>" autofocus type="text" maxlength="50" />
                                </div>
                                <div class="large-6 cell">
                                    Last Name<span class="required">*</span><input name="f_lastname" value="<?=$_SESSION['last_name']?>" type="text" maxlength="50" />
                                </div>
                                <div class="medium-12 cell" style="margin-top:1rem;">
                                    Email Address<span class="required">*</span> <input name="f_email" value="<?=$_SESSION['email']?>" type="text" maxlength="64" />
                                </div>
                                <div class="medium-12 cell">
                                    Phone Number<span class="required">*</span> <input name="f_phone" value="<?=$_SESSION['mobile']?>" type="text" maxlength="20" />
                                </div>
                                <div class="medium-12 cell">
                                    <input name="f_optin_exists" type="hidden" value="1" /> <input name="f_optin" value="1" type="checkbox" CHECKED /><span class="newl">Yes! Please add me to your mailing list today!</span>
                                </div>
                                <div class="medium-12 cell">
                                    <input name="Submit" type="submit" value="Watch the Overview NOW!" />
                                    <p>
                                        Your information is secure and we respect your privacy!
                                    </p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div><!-- ./Medium-5 cell -->
            <div class="medium-7 cell left-cont medium-order-1">
                <!--<video controls autoplay class="lg-video sm-padding-t-b">
                    <source src="//xcorder.s3.amazonaws.com/148/95418575/YUXU44/video/YUXU44_360p.mp4" type="video/mp4">
                    Your browser does not support the video tag.
                </video>-->
                <h1>Looking To Make Some Changes to Your Life?</h1>
                <h2>Here's a realistic solution</h2>

                <div class="sm-padding-t-b show-for-small-only">
                    <script>
                        function isValidPhone2(phone_number)
                        {
                        var phone = phone_number.replace(/[\(\)\.\-\ ]/g, '');
                        if (phone == "") { return false;
                        } else if (isNaN(parseInt(phone))) { return false;
                        } else if (phone.length < 10 || phone.length >= 15) { return false;
                        } return true;
                        }
                        function isValidEmail2(email)
                        {
                        var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
                        if(reg.test(email) == false) { return false; } return true;
                        }
                        function checkForm2(myForm) {
                         var errors = "";
                        if (myForm.f_firstname.value == "") errors = "<li>Please enter your First Name.</li>";
                        if (myForm.f_lastname.value == "") errors += "<li>Please enter your Last Name.</li>";
                        if (!isValidEmail2(myForm.f_email.value)) errors += "<li>Please enter a Valid Email.</li>";
                        if (!isValidPhone2(myForm.f_phone.value)) errors += "<li>Please enter a Valid Phone Number.</li>";

                        if (errors != "") {
                            $('#error2').show();
                            $('#error2 ul').html(errors).show();
                            return false;
                        } else {
                            $('#error2').hide();
                            $('#error2 ul').html('').show();
                            return true;
                            }
                         }
                    </script>
                    <form id="form" action="http://mela-recruit.co.uk.7figuresecrets.com/ms/external" method="post" onSubmit="javascript:return checkForm2(this);" class="form-wrapper">
                        <input type="hidden" name="event" value="lp_form">
                        <input type="hidden" name="sub_event" value="visit1">
                        <input type="hidden" name="revisit_event" value="revisit1">
                        <input type="hidden" name="val_required" value="f_firstname,f_lastname,f_email,f_phone">
                        <input type="hidden" name="category_id" value="6465">
                        <input type="hidden" name="campaign_id" value="3305">
                        <h2 class="text-centerxxx sm-padding-t-b">YES, I want to watch your OVERVIEW and get more FREE INFO asap!</h2>
                        <div class="grid-x grid-padding-x">
                            <div class="medium-12 cell" id="error2">
                                <div class="callout alert-danger">
                                    <ul>
                                        <li></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="medium-6 cell">
                                First Name<span class="required">*</span><input name="f_firstname" autofocus value="<?=$_SESSION['first_name']?>" type="text" maxlength="50" />
                            </div>
                            <div class="medium-6 cell">
                                Last Name<span class="required">*</span><input name="f_lastname" type="text" value="<?=$_SESSION['last_name']?>" maxlength="50" />
                            </div>
                            <div class="medium-12 cell">
                                Email Address<span class="required">*</span> <input name="f_email" type="text" value="<?=$_SESSION['email']?>" maxlength="64" />
                            </div>
                            <div class="medium-12 cell">
                                Phone Number<span class="required">*</span> <input name="f_phone" type="text" value="<?=$_SESSION['mobile']?>" maxlength="20" />
                            </div>
                            <div class="medium-12 cell">
                                <input name="f_optin_exists" type="hidden" value="1" /> <input name="f_optin" value="1" type="checkbox" CHECKED /><span class="newl">Yes! Please add me to your mailing list today!</span>
                            </div>
                            <div class="medium-12 cell">
                                <input name="Submit" type="submit" value="Watch the Overview NOW!" />
                                <p class="small">
                                    Your information is secure and we respect your privacy!
                                </p>
                            </div>
                        </div>
                    </form>
                </div>

                <h3>A Simple, Genuine Solution that is already working for hundreds of thousands of people...</h3>
                <!--<h3>Real people, Real Success, Real income ...a Real Solution for You!</h3>-->
                <ul class="list-d">
                    <li>Earn from <strong>£440</strong> to <strong>£5,000</strong>+ per month, part-time working from home.</li>
                    <li>Free training and unparalleled support while building your contacts.</li>
                    <li>Access to in-house tools that will help you manage your contacts.</li>
                    <li>Work on your terms and your schedule.</li>
                    <li>Working with Industry-leading 30-years providing residual income for tens of thousands of families.</li>
                    <li>No previous experience necessary.</li>
                    <li>Your only requirement is to have a real desire to make some changes to your life, backed by a commitment to take action, just following the steps of our Proven Training System.</li>
                </ul>

                <h2>IMPORTANT:</h2>
                <ol class="list-d">
                    <li>Please make sure you have at least 30-minutes quiet, undisturbed time to watch all the Overview in full</li>
                    <li>Do NOT try and watch the Overview on your Phone - the screen will be too small for you to see everything - please watch on a PC, Laptop or Tablet with a bigger screen.</li>
                    <li>Please have a pen and paper in hand to jot down any questions, and then someone will answer those for you</li>
                </ol>
                <p>Enjoy the Overview!</p>
            </div><!-- ./medium-7 cell left-cont -->
        </div><!--./grid-x grid-padding-x-->
    </div>
</section>
