<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Leads Work')->setSeparator(' | ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icon2.ico'])
            ->prependStylesheet($this->basePath('css/app.css'))
            ->prependStylesheet($this->basePath('css/fonts.css'))
            ->prependStylesheet($this->basePath('css/foundation.custom.css'))
            ->prependStylesheet($this->basePath('css/topbar-responsive.css'))
            ->prependStylesheet('//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css')
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css')
            ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css')
            //->prependStylesheet($this->basePath('css/foundation.min.css'))
        ?>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113167552-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-113167552-1');
        </script>
    </head>
    <body>
        <!-- Scripts -->
        <?= $this->headScript()
        ->prependFile($this->basePath('js/what-input.js'))
        ->prependFile($this->basePath('js/app.js'))
        //->prependFile($this->basePath('js/sup-topbar.min.js')) // Scripts to show top bar on scroll
        ->prependFile('//cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/plugins/foundation.dropdown.min.js')
        ->prependFile('//cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/plugins/foundation.util.keyboard.min.js')
        ->prependFile('//cdn.jsdelivr.net/foundation/6.1.1/js/foundation.accordion.js')
        ->prependFile('//cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/plugins/foundation.core.min.js')
        ->prependFile('//cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js')
        //->prependFile($this->basePath('js/foundation.min.js'))
        ->prependFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js')
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js') // we are using jquery 2.1.4 to support sup-topbar.min.js. 3.2.1 does not support topbar
        ?>
    <style media="screen">
        html, body{
            height: 100%;
            background-color: #FFF;
        }
    </style>
    <header>
        <div class="slideUp landingpage-header open">
            <div class="grid-container">
                <div class="grid-x grid-padding-x">
                    <div class="small-12 medium-12 cell">
                        <!-- mobile nav bar -->
                        <div class="title-bar topbar-center-logo-mobile" data-responsive-toggle="topbar-center-logo" data-hide-for="medium">
                            <div class="title-bar-left">
                                <div class="title-bar-title"><a href="<?= $this->url('home'); ?>"><img src="<?= $this->basePath('img/') ?>logo.png" alt="Leadswork Logo" /></a></div>
                            </div>
                            <div class="title-bar-right">
                                <div class="menu-icon-wrapper" data-toggle="topbar-center-logo">
                                    <span class="menu-icon-1"></span>
                                    <span class="menu-icon-2"></span>
                                    <span class="menu-icon-3"></span>
                                </div>
                            </div>
                        </div>
                        <!-- /mobile nav bar -->

                        <!-- medium and larger nav bar -->
                        <div class="top-bar topbar-center-logo" id="topbar-center-logo">
                            <div class="top-bar-center">
                                <a href="<?= $this->url('home'); ?>"><img src="<?= $this->basePath('img/') ?>logo.png" alt="Leadswork Logo" width=180 /></a>
                            </div>
                            <div class="top-bar-right">
                                <ul class="menu vertical medium-horizontal">
                                    <li><a href="tel:02030262168" title="contact number"><i class="fa fa-phone" aria-hidden="true"></i> 0203 026 2168</a></li>
                                    <li><a href="mailto:support@support@leadswork.co.uk" title="contact email"><i class="fa fa-envelope-o" aria-hidden="true"></i> support@leadswork.co.uk</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- /medium and larger nav bar -->
                    </div>
                </div>
            </div><!-- ./grid-container -->
        </div>
    </header>
    <?= $this->content ?>
    </body>
</html>
